version: "3.7"

services:
  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
  rafisa-app-1:
    build: .
  rafisa-app-2:
    build: .