name: Deploy

on:
  push:
    branches:
      - rafisa-old

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create .nojekyll file
        run: touch .nojekyll
      
      - name: Shut down all running containers and bring them up again
        run: |
          docker compose down
          docker compose build
          docker compose up -d