name: Deploy

on:
  push:
    branches:
      - rafisa-old

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /rafisa-app/production
            git fetch origin rafisa-old
            git pull origin rafisa-old
            cd /rafisa-app/server
            docker compose down
            docker compose build
            docker compose up -d