# Automated deploy to VPS workflow
name: Automated Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  deploy:
    # This workflow will not run directly in the VPS. Instead, it'll run over 
    # a github provided and hosted environment, and from there it will execute
    # remote commands on the VPS through SSH.
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using SSH
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.PASSPHRASE }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        # Shut down every running container and bring them up again
        script: /bin/bash /rafisa-app/deploy-scripts/deploy-testing.sh
