name: Deploy

on:
  push:
    branches:
      - rafisa-old

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm ci 

      - name: Build app
        run: npm run build

      - name: Start app
        run: npm start